<?php
/**
 * Cybage Promotion Discount Plugin 
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available on the World Wide Web at:
 * http://opensource.org/licenses/osl-3.0.php
 * If you are unable to access it on the World Wide Web, please send an email
 * To: Support_Magento@cybage.com.  We will send you a copy of the source file.
 *
 * @category   Promotion Discount Plugin
 * @package    Cybage
 * @copyright  Copyright (c) 2014 Cybage Software Pvt. Ltd., India
 *             http://www.cybage.com/pages/centers-of-excellence/ecommerce/ecommerce.aspx
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Cybage Software Pvt. Ltd. <Support_Magento@cybage.com>
 */
    $_source  = $this->getSource();
    $_order   = $this->getOrder();
    $this->setPriceDataObject($_source);
    /**
    *Start of code to display Discount EC
    */
    $currencyCode   = '';
    $currency       = $_order->getOrderCurrency(); 
    if (is_object($currency)) {
        $currencyCode = $currency->getCurrencyCode();
    }
    $currencySymbol = Mage::app()->getLocale()->currency($currencyCode)->getSymbol();
?>
<?php if ((float) $_source->getDiscountAmount()): ?>
    <?php if($_order->getCouponDiscount()>0):?>
        <tr>
            <td class="label">
                <?php echo Mage::helper('sales')->__('Coupon Discount (%s)', $_order->getCouponCode()) ?>
            </td>
            <td><span class="price"><?php echo "-".$currencySymbol.number_format($_order->getCouponDiscount(),2) ?></span></td>
        </tr>
    <?php endif; ?>
    <?php if($_order->getPromotionalDiscount()>0):?>
        <tr>
            <td class="label">
                <?php echo $_order->getPromoLable() ?>
            </td>
            <td><span class="price"><?php echo "-".$currencySymbol.number_format($_order->getPromotionalDiscount(),2) ?></span></td>
        </tr>
    <?php endif;?>
    <?php if(!($_order->getCouponDiscount()) && !($_order->getPromotionalDiscount())):?>
    <tr>
        <td class="label">
            <?php if ($_order->getCouponCode()): ?>
                <?php echo Mage::helper('sales')->__('Discount (%s)', $_order->getCouponCode()) ?>
            <?php else: ?>
                <?php echo Mage::helper('sales')->__('Discount') ?>
            <?php endif; ?>
        </td>
        <td><?php echo $this->displayPriceAttribute('discount_amount') ?></td>
    </tr>
<?php endif; ?>
<?php endif;?>