<?php
/**
 * Cybage Promotion Discount Plugin 
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available on the World Wide Web at:
 * http://opensource.org/licenses/osl-3.0.php
 * If you are unable to access it on the World Wide Web, please send an email
 * To: Support_Magento@cybage.com.  We will send you a copy of the source file.
 *
 * @category   Promotion Discount Plugin
 * @package    Cybage
 * @copyright  Copyright (c) 2014 Cybage Software Pvt. Ltd., India
 *             http://www.cybage.com/pages/centers-of-excellence/ecommerce/ecommerce.aspx
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Cybage Software Pvt. Ltd. <Support_Magento@cybage.com>
 */
?>
<?php $currentUrl = $this->helper('core/url')->getCurrentUrl(); ?>
<table cellspacing="0" width="100%">
    <col />
    <col width="1" />
    <?php $_totals = $this->getTotals('footer')?>
    <?php if ($_totals):?>
    <tfoot>
    <?php foreach ($this->getTotals('footer') as $_code => $_total): ?>
        <?php if ($_total->getBlockName()): ?>
            <?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
        <?php else:?>
        <tr class="<?php echo $_code?>" style="padding:0 0 0 4px";>
            <td <?php echo $this->getLabelProperties()?> class="label">
                <strong><?php echo $this->escapeHtml($_total->getLabel()); ?></strong>
            </td>
            <td <?php echo $this->getValueProperties()?> class="emph">
                <strong><?php echo $this->formatValue($_total) ?></strong>
            </td>
        </tr>
        <?php endif?>
    <?php endforeach?>
    </tfoot>
    <?php endif?>

    <?php $_totals = $this->getTotals('')?>
    <?php if ($_totals):?>
    <tbody>
    <?php foreach ($_totals as $_code => $_total): ?>
        <?php $totalData = $_total->getData(); ?>
        <?php if ($_total->getBlockName()): ?>
            <?php if (strpos($currentUrl,'sales_order/') == false) :?>
                <?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
            <?php endif; ?>
        <?php else:?>
            <?php if( $totalData['code'] != 'discount'): ?>
                <tr class="<?php echo $_code?>"  style="padding:0 0 0 4px";>
                    <td <?php echo $this->getLabelProperties()?> class="label">
                        <?php if ($_total->getStrong()):?>
                        <strong><?php echo $this->escapeHtml($_total->getLabel()); ?></strong>
                        <?php else:?>
                        <?php echo $this->escapeHtml($_total->getLabel()); ?>
                        <?php endif?>
                    </td>
                    <?php if ($_total->getStrong()):?>
                    <td <?php echo $this->getValueProperties()?> class="emph">
                        <strong><?php echo $this->formatValue($_total) ?></strong>
                    <?php else:?>
                    <td <?php echo $this->getValueProperties()?>>
                        <?php echo $this->formatValue($_total) ?>
                    <?php endif?>
                    </td>
                </tr>
            <?php endif?>
        <?php endif?>
    <?php endforeach?>
    </tbody>
    <?php endif?>
</table>
