<?php
/**
 * Cybage Promotion Discount Plugin 
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available on the World Wide Web at:
 * http://opensource.org/licenses/osl-3.0.php
 * If you are unable to access it on the World Wide Web, please send an email
 * To: Support_Magento@cybage.com.  We will send you a copy of the source file.
 *
 * @category   Promotion Discount Plugin
 * @package    Cybage
 * @copyright  Copyright (c) 2014 Cybage Software Pvt. Ltd., India
 *             http://www.cybage.com/pages/centers-of-excellence/ecommerce/ecommerce.aspx
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Cybage Software Pvt. Ltd. <Support_Magento@cybage.com>
 */
?>
<?php $label = $this->getCouponLabelValue($this->getTotals());?>
<?php foreach ($this->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
    <?php else:?>
            <?php
            /**
             * Start of Show Discount label for EC.
             */
            if ($_code == 'discount' && ($this->getOrder()->getCouponDiscount() || $this->getOrder()->getPromotionalDiscount()))
            { ?>
            <?php foreach ($label as $key => $value) { ?>
                    <tr class="<?php echo $key ?>">
                        <td <?php echo $this->getLabelProperties() ?>>
                            <?php echo $this->__($value['label']).":" ?>
                        </td>
                        <td <?php echo $this->getValueProperties() ?>>
                        <?php echo "-".$this->helper('checkout')->formatPrice($value['value']) ?>
                        </td>
                    </tr>
                <?php }
            /**
             * End of Show Discount label for EC.
             */
            } else { ?>
    <tr class="<?php echo $_code?>">
        <td <?php echo $this->getLabelProperties()?>>
            <?php if ($_total->getStrong()):?>
            <strong><?php echo $this->escapeHtml($_total->getLabel());?></strong>
            <?php else:?>
            <?php echo $this->escapeHtml($_total->getLabel());?>
            <?php endif?>
        </td>
        <td <?php echo $this->getValueProperties()?>>
            <?php if ($_total->getStrong()):?>
            <strong><?php echo $this->formatValue($_total) ?></strong>
            <?php else:?>
            <?php echo $this->formatValue($_total) ?>
            <?php endif?>
        </td>
    </tr>
    <?php }
    endif?>
<?php endforeach?>
